spring:
  application:
    name: coffee-erp-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_inventory
    username: coffee_admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000            # 1 day in milliseconds